### ISSUE TITLE
Voice box always open

### ISSUE THREAD

**Issue by LConerly** [mdbridge/click-by-voice#1]
I have a student that uses mouseless browsing on Firefox and we are hoping to change to Chrome by using Click by Voice. She is nonverbal and very smart. Is there a way to keep the box open all of the time so she can type the number she needs?

**Comment by mdbridge** [comment]
That would be easy enough to add.  She might prefer the cVim  extension, however, as it has  many more keyboard commands for things that people like me perform via voice commands.

**Comment by LConerly** [comment]
Thank you. However, she is a nonverbal student.  She has to use the keyboard. She needs to reduce the number of keystrokes. I didn’t see that available on cVim.  Will you let me know when either cVim or Click by Voice is available without having to open an additional box?  Currently she uses Firefox but we are a Google district and much of her classwork is in Google. She can’t copy and paste. Thank you so much for your help. She is a very brilliant student, just needs some additional help.

**Comment by mdbridge** [comment]
Sorry, I haven't had the bandwidth to deal with this.  I hope you found an alternative solution.  Given my limited bandwidth, I intend to concentrate on making click-by-voice work as well as possible with voice commands.

**Comment by mdbridge** [comment]
aka, I'm categorizing this as won't fix
