### ISSUE TITLE
Prevent an Element from Getting a Hint 

### ISSUE THREAD

**Issue by Mark-Phillipson** [mdbridge/click-by-voice#2]
If I'm creating a website is there a class I can give an element to prevent it from getting a hint number?

I'm using Bootstrap 3 accordion and for each tab CbV is creating a hint number that causes the tab to take up two lines instead of one.

I can hide all the hints, but I would rather just hide the hints for the tab elements if possible :-)

![bootstrap3accordioncbv](https://user-images.githubusercontent.com/16239024/41861623-ba165790-7899-11e8-9762-49759b6257ee.png)

**Comment by mdbridge** [comment]
There isn't such a class.    If it's just for you, there is an experimental show hints switch, ^{...} that causes elements matching CSS selector ... to not be hinted.  So, if your class is foobar, you could use :+^{.foobar} as your show hints command.  Overlay mode, of course, won't have this problem but may make other parts of the page harder to read.
Without the DOM to look at, I can't take a guess at why hybrid mode thinks it's safe to use an inline hint for the tabs.

**Comment by Mark-Phillipson** [comment]
Okay will use the experimental show hints switch.
