### ISSUE TITLE
Mouse numbers always on

### ISSUE THREAD

**Issue by L13w** [mdbridge/click-by-voice#9]
Mouse numbers are always on on all websites. Is there a way to disable this? I only want mouse numbers on when I say "Mouse Numbers On" in Dragon.

**Comment by mdbridge** [comment]
Hi L13w.

You can set up your config so it starts with hints off; see https://github.com/mdbridge/click-by-voice/blob/master/doc/displaying_hints.md 

See "... unless the CbV option "Startup show numbers command" has been set, which case it uses that command instead. If you want CbV to start up without using hints, use :- as the value of this option." there.

Then you can turn hints on  just for the current display of the current page via the command ":once+"
Remember that you are responsible for writing/obtaining your own Dragon commands.

**Comment by mdbridge** [comment]
Note that you can also set up your config so that hints are on for some websites and off by others by default.
